name: CI

on: [pull_request, push]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Build
        run: nr build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Typecheck
        run: nr typecheck
  demo:
    name: Demo
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Build Demo
        run: nr demo
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Lint
        run: nr lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Test
        run: nr test
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, typecheck, demo, lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
     steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v2.7.0
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
